site_name: BirdTalk
site_url: https://membot.com/btdoc.html
markdown_extensions:
  - attr_list
  - md_in_html
theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.path
    - search.suggest
    - search.highlight
    - toc.integrate
    #- header.autohide
  font:
    text: Roboto
  palette:
    scheme: default
    primary: indigo
    accent: blue
  icon:
    logo: material/book-open-variant
extra_css:
  - stylesheets/extra.css

nav:
  - About: index.md
  - Why: testimonial.md
  - Install: installation/requirements-and-setup.md
  - Start: getting-started.md
  - Upload: uploading-checklists.md
  - Reference: commands/reference.md
  - Tips: tips-and-tricks.md
  - FAQ: faq.md

repo_url: ""  # Hide GitHub link
edit_uri: ""  # Hide edit button

extra:
  generator: false  # Hide "Made with Material for MkDocs"
